# Databricks notebook source
# MAGIC %pip install mlflow==2.10.1 lxml==4.9.3 transformers==4.30.2 langchain==0.1.5 databricks-vectorsearch==0.22 databricks-sdk==0.28.0 databricks-feature-store==0.17.0
# MAGIC %pip install dspy-ai -U
# MAGIC dbutils.library.restartPython()

# COMMAND ----------

# MAGIC %run ./config

# COMMAND ----------

# MAGIC %run ../../_resources/00-init $reset_all_data=false

# COMMAND ----------

sql(f"CREATE CATALOG IF NOT EXISTS {catalog};")
sql(f"USE CATALOG {catalog};")
sql(f"CREATE SCHEMA IF NOT EXISTS {dbName};")
sql(f"USE SCHEMA {dbName};")
sql(f"CREATE VOLUME IF NOT EXISTS {volume};")

# COMMAND ----------

# すでに同名のテーブルが存在する場合は削除
sql(f"drop table if exists {team_master_bronze_table_name}")

# 生データを読み込み、デルタ・テーブルを作成して保存
raw_data_url = "https://raw.githubusercontent.com/hiouchiy/Pratical_RAG_Project/refs/heads/main/medallioncard/agent/team_master.json"
!wget $raw_data_url -O /tmp/team_master.json

unity_catalog_volume_path = f'/Volumes/{catalog}/{dbName}/{volume}/team_master.json'
!cp /tmp/team_master.json $unity_catalog_volume_path

spark.read.option("multiline","true").json(unity_catalog_volume_path).write.mode('overwrite').saveAsTable(team_master_bronze_table_name)

display(spark.table(team_master_bronze_table_name))

# COMMAND ----------

sql(f"DROP TABLE IF EXISTS {team_master_silver_table_name};")

sql(f"""
--インデックスを作成するには、テーブルのChange Data Feedを有効にします
CREATE TABLE IF NOT EXISTS {team_master_silver_table_name} (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  team_id STRING NOT NULL,
  team_code STRING NOT NULL,
  team_name STRING NOT NULL,
  description STRING NOT NULL
) TBLPROPERTIES (delta.enableChangeDataFeed = true); 
""")

from pyspark.sql.functions import lit, to_date, col
spark.table(team_master_bronze_table_name).write.mode('overwrite').saveAsTable(team_master_silver_table_name)

comment = """このテーブルは会社のチームのマスタ情報です。team_idやteam_codeなどの検索に使用します。"""

spark.sql(f'COMMENT ON TABLE {team_master_silver_table_name} IS "{comment}"')

display(spark.table(team_master_silver_table_name))

# COMMAND ----------



# COMMAND ----------

sql(f"""
DROP FUNCTION {catalog}.{dbName}.search_team_info
""")

# COMMAND ----------


